### PR TITLE
Emotion API added.

### PR DESCRIPTION
**Pull request by moeenz**
Emotion API is now added to project as 'projectoxford.emotion' module.

### CODE REVIEW

**Comment by zooba** [comment]
Thanks for this, @moeenz! There's just a few things that I'd like to see changed in the API before merging it in.
- I _really_ don't like the hard dependency on numpy, etc. If you're only dealing with image file data it shouldn't be necessary, so it shouldn't fail until you try to use functionality that needs it
- not a fan of a module named `api`. Is there any reason not to just put the client in `projectoxford.emotion`? Same with the `utils` module
- I'd rather have separate functions than Boolean parameters, e.g. `process_image_from_bytes`, `process_image_from_path`, `process_image_from_url`
- helper functions for quick summaries are also better than bool parameters. e.g. `img2 = ec.render_emotion(img)`, `ec.get_strongest_emotion(img) -> 'happy', etc.`
- on a more minor note, I won't accept camel case anywhere :)

Otherwise, I really like it! And thanks for going through the URLs for me.

If you're not interested or don't have time to make more changes, I'm happy to merge as-is and go through it myself. But if you want to do it and update the PR, feel free.

**Comment by zooba** [comment]
I'd also like it if you signed the [Microsoft CLA](http://cla.microsoft.com), since this may become an official project one day (right now it's sample code, which is why it isn't under the Microsoft organisation with automatic CLA handling). Otherwise it may prevent this ever becoming a truly official library.

**Comment by moeenz** [comment]
- "emotion" module is now moved to "projectoxford".
- I reformed the module and results are now available within EmotionResult objects which have the ability to do methods like `get_raw_result`, `get_strongest_emotion`, `render_emotion`.
- numpy, opencv and matplotlib are now only needed in `render_emotion` method.
- I also signed the [Microsoft CLA](http://cla.microsoft.com/).

**Comment by zooba** [comment]
Awesome, thanks. (Sorry about the delay - been very busy getting ready for PyCon next week.)

**Comment by moeenz** [comment]
No problem, I will try to add other APIs as well whenever I got time.

**Pull request merged**
